version: '3'

services:
  zola:
    build: .
    command: serve --interface 0.0.0.0 --port 8080 --base-url localhost --drafts
    user: "1000:100"
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
      - "1111:1111"
      - "1024:1024"
    container_name: zola-server